terms_list = ['after happiness',
'career advancement',
'fullest potential',
'success formula']


# terms_list = ['after happiness',
# 'career advancement',
# 'fullest potential',
# 'success formula',
# 'professional growth',
# 'formula for success',
# 'finding happiness',
# 'change your thinking',
# 'positive psychology',
# 'self-improvement',
# 'motivational books',
# 'personal success',
# 'professional success',
# 'personal growth',
# 'self improvement',
# 'self-help',
# 'positive thinking',
# 'positive genius',
# 'achieving happiness',
# 'science of happiness',
# 'positive inception',
# 'achieving success',
# 'positive inspiration',
# 'success accelerants',
# 'spreading happiness',
# 'positive change',
# 'navigating the workplace',
# 'first job after college',
# 'career advancement',
# 'AEI',
# 'getting what you want',
# 'college graduation books',
# 'American Enterprise Institute',
# 'professional growth',
# 'soft skills',
# 'college graduation gifts',
# 'career advice',
# 'college graduation gift',
# 'adult life',
# 'bad boss',
# 'professional success',
# 'personal success',
# 'graduation books',
# 'career success',
# 'living well',
# 'workplace culture',
# 'communication skills',
# 'personal development',
# 'office manners',
# 'getting ahead',
# 'professional writing',
# 'living a good life',
# 'corporate ladder',
# 'professional growth',
# 'professional success',
# 'getting ahead',
# 'business classics',
# 'collaborative management',
# 'power of relationships',
# 'getting what you want',
# 'making friends',
# 'making connections',
# 'connecting to people',
# 'personal success',
# 'personal growth',
# 'relationship building',
# 'business classic',
# 'connecting',
# 'business success',
# 'social media networking',
# 'communication skills',
# 'meaningful relationships',
# 'meaningful connections',
# 'connecting to the world',
# 'networking',
# 'business relationships',
# 'IHHP',
# 'handling stress',
# 'nerves of steel',
# 'interview stress',
# 'business psychology',
# 'overcoming obstacles',
# 'personal improvement',
# 'power of pressure',
# 'pressure solutions',
# 'decision-making',
# 'personal success',
# 'decision making',
# 'self-help',
# 'stress management',
# 'self improvement',
# 'self help',
# 'professional success',
# 'business success',
# 'COTE',
# 'nature of pressure',
# 'face pressure',
# 'pressure traps',
# 'pressure management',
# 'performance under pressure',
# 'decisions under pressure',
# 'success under pressure',
# 'handling pressure',
# 'health and human potential',
# 'performance anxiety',
# 'startup founders',
# 'job for tomorrow',
# 'intelligent risk',
# 'add value',
# 'personal brand',
# 'career growth',
# 'build a career',
# 'business inspiration',
# 'personal branding',
# 'adding value',
# 'professional growth',
# 'professional inspiration',
# 'building a career',
# 'career plans',
# 'entrepreneurship',
# 'professional development',
# 'your brand',
# 'personal development',
# 'success stories',
# 'career guide',
# 'career guides',
# 'personal success',
# 'personal growth',
# 'founders',
# 'startup success',
# 'startup',
# 'adapt to the future',
# 'transform your career',
# 'invest in yourself',
# 'lifeline relationships',
# 'inner circle',
# 'building deep relationships',
# 'deep relationships',
# 'building trusting relationships',
# 'dream team',
# 'trusting relationships',
# 'existential intelligence',
# 'self help',
# 'business',
# 'relationships',
# 'networking',
# 'self-help',
# 'building relationships',
# 'building trust',
# 'self improvement',
# 'self-improvement',
# 'leadership',
# 'career development',
# 'making connections',
# 'goal-setting',
# 'sparring',
# 'corporate sparring',
# 'building relationships at work',
# 'professional relationships',
# 'trusted team',
# 'meaningful connections',
# 'creativity',
# 'creative genius',
# 'disruptive innovation',
# 'rediscover creativity',
# 'innovation',
# 'breakthrough creativity',
# 'rethink',
# 're-think',
# 'creative',
# 'personal improvement',
# 'personal success',
# 'achieve potential',
# 'achieving potential',
# 'full potential',
# 'unlock potential',
# 'unlocking potential',
# 'self growth',
# 'art',
# 'self discovery',
# 'self-discovery',
# 'know yourself',
# 'unlock your potential',
# 'unlocking your creativity',
# 'unlock your creativity',
# 'unleash creativity',
# 'unleash genius',
# 'philosophy of creativity',
# 'creative value',
# 'outside the box thinking',
# '37 signals',
# 'callaboration',
# 'co-working space',
# 'business',
# 'work from home',
# 'virtual workspace',
# 'telecommuting',
# 'remote work',
# 'remote jobs',
# 'real estate footprint',
# 'work at home jobs',
# 'work from home opportunities',
# 'work at home',
# 'work from home moms',
# 'working from home',
# 'work from home careers',
# 'telecommuting jobs',
# 'telecommute',
# 'virtual office space',
# 'under one roof',
# 'remote business',
# 'work remotely',
# 'working remotely',
# 'work remotely from home',
# 'commute',
# 'work from home jobs',
# 'business psychology',
# 'essentialist',
# 'essential',
# 'minimalism',
# 'minimalist',
# 'essential living',
# 'how to be more produtive',
# 'how to be more productive at work',
# 'being more productive',
# 'increase productivity',
# 'increasing productivity',
# 'increased productivity',
# 'productivity tools',
# 'achieve more',
# 'mental clairty',
# 'mental focus',
# 'design your life',
# 'time management',
# 'time management skills',
# 'time management tools',
# 'effective time management',
# 'power of choice',
# 'what really matters',
# 'vital few',
# 'trivial many',
# 'less but better',
# 'less is more',
# 'psychology',
# 'digital reputation',
# 'reputation management',
# 'digital footprint',
# 'digital future',
# 'online reputation management',
# 'brand reputation',
# 'online reputation',
# 'personal data',
# 'personalized data',
# 'privacy management',
# 'reputation.com',
# 'data privacy',
# 'online privacy',
# 'online presense',
# 'privacy settings',
# 'privacy issues',
# 'digital privacy',
# 'digital privacy issues',
# 'online privacy issues',
# 'social media privacy',
# 'millenial privacy',
# 'reputation economics',
# 'privacy advocate',
# 'social media mistakes',
# 'personal data collection',
# 'personal data protection',
# 'reputation rich',
# 'power of reputation',
# 'Maine',
# 'orchard',
# 'apple',
# 'apple orchard',
# 'love triangle',
# 'psychic',
# 'premonitions',
# 'Amish cooking',
# 'Amish recipes',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'Maine',
# 'orchard',
# 'apple',
# 'apple orchard',
# 'gardening',
# 'garden',
# 'psychic',
# 'premonitions',
# 'Amish cooking',
# 'Amish recipes',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'prayer',
# 'rape',
# 'shunning',
# 'Mennonite',
# 'Amish quilt',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'culture clash',
# 'single parent',
# 'parenthood',
# 'widow',
# 'widowhood',
# 'conversion',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'Amish',
# 'christian fiction',
# 'amish fiction',
# 'pennsylvania',
# 'Florida',
# 'Spring',
# 'brothers',
# 'restaurant',
# 'diner',
# 'novella',
# 'Mennonite',
# 'Amish cooking',
# 'Amish recipes',
# 'orchard',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'holiday',
# 'Christmas',
# 'Advent',
# 'novella',
# 'mistaken identity',
# 'arts and crafts',
# 'arts & crafts',
# 'woodworking',
# 'woodworker',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'amish fiction',
# 'christian fiction',
# 'twins',
# 'twin',
# 'switched at birth',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'B&B',
# 'BNB',
# 'bed and breakfast',
# 'bed & breakfast',
# 'Kansas',
# 'mistaken identity',
# 'Mennonite fiction',
# 'Amish Romance',
# 'Christian Fiction',
# 'Christian Literature',
# 'Christian Romance',
# 'Contemporary Christian Romance',
# 'Contemporary Religious Fiction',
# 'Religious Fiction',
# 'Religious Romance',
# 'Women%27s Christian Fiction',
# 'Women%27s Religious Fiction',
# 'Contemporary Christian Fiction',
# 'amish fiction',
# 'clean fiction',
# 'clean reads',
# 'clean romance',
# 'inspirational romance',
# 'inspirational fiction',
# 'bonnet',
# 'plain',
# 'buggy',
# 'Kapp',
# 'Englischer',
# 'Old Order Amish',
# 'Old Order Mennonite',
# 'Mennonite Romance']